spring:


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true


logging:
  level:
    org:
      springframework:
        web: debug
    sql: debug
server:
  port: 8083
  servlet:
    context-path: /api


