spring:
  datasource:
    url: jdbc:mariadb://ec2-34-199-120-230.compute-1.amazonaws.com:3306/s07p11c208?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ssafy
    password: ssafy

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: debug
    sql: debug



